server:
  port: 8082

spring:
  application:
    name: ms-product
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USER:postgres}
    password: ${SPRING_DATASOURCE_PASS:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}

payment-service:
  base-url: http://localhost:8084/api/v1/internal/payments